### ISSUE TITLE
Is there a complete demo you could provide?

### ISSUE THREAD

**Issue by tfarina** [galeo/web.py-auth#1]
I'm having trouble to setup a complete example using this API.

**Comment by romainp** [comment]
Hello, a demo would definetely help. Do you have a bit more info on how to use the automatic views? I have difficulties implementing login page etc..

**Comment by galeo** [comment]
Hi, @tfarina @romainp 
Sorry for the late reply. A simple demo will be soon added, please check later.

**Comment by galeo** [comment]
Hi, @tfarina @romainp 
I have already add a simple demo app, please check.

**Comment by romainp** [comment]
EDIT: declaring all the authentication related variables in a separate file fixed the issue. Thanks for the demo again. 

Hi @galeo, 
Thanks a lot for the demo, it helps. When I try to use @auth.protected in separate files of the project it creates a redirect loop. Would you know how to fix that? Or how to use @auth.protected in other files than the one where auth is initialized?
Thanks.

**Comment by galeo** [comment]
Hi, @romainp 
You may want to check the `url_after_login` option when initializing the **auth** instance if a redirect loop error occurred.

You could initialize the **auth** instance in a separate file module, then use it anywhere you want by **importing** it. 

Hope this would help you.
