### ISSUE TITLE
license information

### ISSUE THREAD

**Issue by unDocUMeantIt** [galeo/web.py-auth#3]
hi, thanks for sharing this module. since there's no LICENSE file yet, it's hard to use the code in other projects, which i assume is something you'd like to see. would you consider adding proper licensing information (GPL2/3, MIT, Apache, whatever...)?

**Comment by galeo** [comment]
The code is licensed under MIT, feel free to use it in any way.

**Comment by unDocUMeantIt** [comment]
thanks, that was quick :)
